### PR TITLE
Added shortcut key.

### PR DESCRIPTION
**Pull request by sidntrivedi**
Added Ctrl+Shift+H as shortcut key for firing up Harbor.

### CODE REVIEW

**Comment by sidntrivedi** [comment]
@saranshbarua @ryzokuken Please review.

**Review by ryzokuken — CHANGES_REQUESTED** [review]
@sidntrivedi012 please fix the indentation.

@saranshbarua PTAL.

**Comment by sidntrivedi** [comment]
@ryzokuken @saranshbarua Done. PTAL.

**Review by ryzokuken — APPROVED** [review]
LGTM. @saranshbarua your thoughts?

**Comment by sidntrivedi** [comment]
@saranshbarua @ryzokuken If any other shortcut key would be more convenient, please tell. Will change it. I had used H to resemble Harbor.

**Comment by saranshbarua** [comment]
Looks good. Merging this.

**Pull request merged**
