### PR TITLE
Initialize extension structure

### PR DESCRIPTION
**Pull request by saranshbarua**
Made the basic structure for the extension. Will add the icons soon.

### CODE REVIEW

**Comment by saranshbarua** [comment]
@ryzokuken @homuncculus  have a look at this. Let's start working.

**Comment by vaibhavk** [comment]
@saranshbarua  ok, starting today

**Comment by V1shvesh** [comment]
@saranshbarua Can we merge this?

**Comment by saranshbarua** [comment]
@V1shvesh I think yes. This is the most basic start.

**Pull request merged**
